### Manipulação Básica de Tensores

In [7]:
# Soma e Produto entre tensores
import torch

# criando tensores
x = torch.tensor([1.0, 2.0, 3.0]) # Define um tensor 1D com três elementos
y = torch.tensor([4.0, 5.0, 6.0]) # outro tensor 1D

# operacao simples
soma = x + y
produto = x * y

print("Soma: ", soma)
print("Produto: ", produto)

Soma:  tensor([5., 7., 9.])
Produto:  tensor([ 4., 10., 18.])


In [8]:
# Operações de Redução e Dimensão
import torch

# criando um tensor 2D(matriz)
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Soma total de todos os elementos
soma_total = torch.sum(x)
print("Soma total: ", soma_total)

# Média dos elementos em cada coluna
media_colunas = torch.mean(x, dim=0)
print("Média das colunas: ", media_colunas)

# Soma dos elementos em cada linha
soma_linhas = torch.sum(x, dim=1)
print("Soma das linhas: ", soma_linhas)

Soma total:  tensor(21.)
Média das colunas:  tensor([2.5000, 3.5000, 4.5000])
Soma das linhas:  tensor([ 6., 15.])


In [9]:
# Manipulação e Transformação de Tensores
import torch

# criando um tensor 1D
x = torch.tensor([1, 2, 3, 4, 5, 6])

# Redimensionando o tensor (transformando 2x3)
x_reshape = x.view(2, 3)
print("Tensor redimensionado para 2x3:\n ", x_reshape)

# Convertendo um tensor em um tensor float
x_float = x.float()
print("Tensor como float: ", x_float)

# Expandindo o tensor para uma nova dimensao
x_unsqueeze = x.unsqueeze(0)  # Adiciona uma nova dimensão no começo
print("Tensor com uma nova dimensao:\n ", x_unsqueeze)

Tensor redimensionado para 2x3:
  tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor como float:  tensor([1., 2., 3., 4., 5., 6.])
Tensor com uma nova dimensao:
  tensor([[1, 2, 3, 4, 5, 6]])


In [10]:
# Operações de Transposição e Produto Matricial
import torch

# criando tensores 2D (matrizes)
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Transposicao de uma matriz
a_transposta = a.t()
print("Transposição de a:\n", a_transposta)

# Produto matricial (multiplicação de matriz)
produto_matriz = torch.matmul(a, b)
print("Produto matricial de a e b:\n", produto_matriz)

Transposição de a:
 tensor([[1, 3],
        [2, 4]])
Produto matricial de a e b:
 tensor([[19, 22],
        [43, 50]])


In [11]:
# Operações de Comparação e Indexação com Tensores
import torch

# criando um tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# comparacao elemento a elemento
maior_que_dois = x > 2
print("Elementos maiores que 2:", maior_que_dois)

# Extraindo os elementos que atendem a uma condição
filtro = x[x > 2]
print("Elementos filtrados:", filtro)

# Indexação por posição
print("Primeiro elemento:", x[0])
print("Últimos dois elementos:", x[-2:])

Elementos maiores que 2: tensor([False, False,  True,  True,  True])
Elementos filtrados: tensor([3., 4., 5.])
Primeiro elemento: tensor(1.)
Últimos dois elementos: tensor([4., 5.])
